---
- name: add user to group
  ansible.builtin.user:
    name: "{{ microk8s_user }}"
    groups: microk8s
    append: true
  with_items: '{{ microk8s_users }}'
  loop_control:
    loop_var: microk8s_user
    label: '{{ microk8s_user }}'
  tags:
    - microk8s
    - microk8s.user
    - microk8s.user.group

- name: Create .kube folder for the user
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    owner: '{{ microk8s_user }}'
    group: '{{ microk8s_user }}'
    mode: 0750
  become: true
  become_user: '{{ microk8s_user }}'
  with_items: '{{ microk8s_users }}'
  loop_control:
    loop_var: microk8s_user
    label: '{{ microk8s_user }}'
  tags:
    - microk8s
    - microk8s.kube
    - microk8s.kube.dir

- name: create kubectl config
  ansible.builtin.shell:
    cmd: microk8s config > ~/.kube/config
  args:
    executable: /bin/bash
    creates: ~/.kube/config
  become_user: '{{ microk8s_user }}'
  environment:
    PATH: '${PATH}:/snap/bin/'
  with_items: '{{ microk8s_users }}'
  loop_control:
    loop_var: microk8s_user
    label: '{{ microk8s_user }}'
  tags:
    - molecule-idempotence-notest
    - microk8s
    - microk8s.kube
    - microk8s.kube.config

- name: reaffirm permission on config directory
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    owner: '{{ microk8s_user }}'
    group: '{{ microk8s_user }}'
    recurse: true
  with_items: '{{ microk8s_users }}'
  loop_control:
    loop_var: microk8s_user
    label: '{{ microk8s_user }}'
  tags:
    - microk8s
    - microk8s.kube
    - microk8s.kube.permission

- name: reaffirm permission on config file
  become_user: '{{ microk8s_user }}'
  ansible.builtin.file:
    path: ~/.kube/config
    state: file
    owner: '{{ microk8s_user }}'
    group: '{{ microk8s_user }}'
    mode: 0600
  with_items: '{{ microk8s_users }}'
  loop_control:
    loop_var: microk8s_user
    label: '{{ microk8s_user }}'
  tags:
    - microk8s
    - microk8s.kube
    - microk8s.kube.permission
...
