---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: ansible-role-microk8s
      vars:
        microk8s_users: ['vagrant', 'root']
        microk8s_plugins:
          dns: true
        microk8s_dns_corefile: |
          some.domain.local.de:53 {
            forward . 192.168.0.1
          }
          .:53 {
            errors
            health {
              lameduck 5s
            }
            ready
            log . {
              class error
            }
            kubernetes cluster.local in-addr.arpa ip6.arpa {
              pods insecure
            }
            prometheus :9153
            forward . 8.8.8.8 
            cache 30
            loop
            reload
            loadbalance
          }
...
