---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
driver:
  name: vagrant
platforms:
  - name: vagrant-ubuntu
    box: ubuntu/focal64
    memory: 4096
    cpus: 2
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 8081, host: 30080"
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 1
...
