---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
platforms:
  - name: molecule-microk8s-default
    box: cloud-image/ubuntu-24.04
    memory: 4096
    cpus: 2
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 1
  log: true
  lint:
    name: ansible-lint
  scenario:
    name: default
...
